# Generated by Django 3.0.5 on 2020-10-30 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_auto_20201030_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity_periods',
            name='pid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='info', serialize=False, to='apis.Activity_user'),
        ),
        migrations.AlterField(
            model_name='activity_user',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
