# Generated by Django 3.0.5 on 2020-10-30 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_auto_20201030_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity_periods',
            name='id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_info', serialize=False, to='apis.Activity_user', unique=True),
        ),
    ]
