# Generated by Django 3.0.5 on 2020-10-30 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_auto_20201030_2121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity_periods',
            old_name='id',
            new_name='pid',
        ),
    ]
